openapi: "3.0.3"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
  - name: internal
paths:
  /pets:
    $ref: './routes/pets.yml'

  /pets/{petId}:
    $ref: './routes/pet.yml'








