import "./App.css";
import "./components/Components.css";

import { useEffect, useState } from "react";
import { DesignerPage } from "./pages/designer/DesignerPage.js";

function App() {
  const [data, setData] = useState<Awaited<ReturnType<typeof importSpec>>>();

  useEffect(() => {
    importSpec().then((_data) => {
      setData(_data);
      console.log("data fetched", _data);
    });
  }, []);

  if (!data) return <>No Data!</>;

  return (
    <>
      <DesignerPage></DesignerPage>
    </>
  );
}

async function importSpec() {
  return {
    api: {
      openapiVersion: "3.0.3",
      info: {
        title: "Inventory Management Test API",
        version: "1.0.0",
        description: "Testapi",
      },
    },
    schemas: [
      {
        id: "#/components/schemas/RegisterResponse",
        name: "RegisterResponse",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/LoginResponse",
        name: "LoginResponse",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/LoginRequest",
        name: "LoginRequest",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/InventoryStockItem",
        name: "InventoryStockItem",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/InventoryStockHistory",
        name: "InventoryStockHistory",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/InventoryStock",
        name: "InventoryStock",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/InventoryItemStats",
        name: "InventoryItemStats",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/WeightUnit",
        name: "WeightUnit",
        kind: "ENUM",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/Weight",
        name: "Weight",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/ItemType",
        name: "ItemType",
        kind: "ENUM",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/Product",
        name: "Product",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/InventoryItem",
        name: "InventoryItem",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/InventorySummaryResponse",
        name: "InventorySummaryResponse",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/ChangeItemDetails",
        name: "ChangeItemDetails",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/ChangeItemRequest",
        name: "ChangeItemRequest",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/SuccessResponse",
        name: "SuccessResponse",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/UpdateItemRequestDetails",
        name: "UpdateItemRequestDetails",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/UpdateItemRequest",
        name: "UpdateItemRequest",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/PurchasedEventDetailBase",
        name: "PurchasedEventDetailBase",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/PurchasedEventDetailItemProduct",
        name: "PurchasedEventDetailItemProduct",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/PurchasedEventDetailItemSpecified",
        name: "PurchasedEventDetailItemSpecified",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/PurchasedEventDetailItem",
        name: "PurchasedEventDetailItem",
        kind: "UNION",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/PurchasedEventDetail",
        name: "PurchasedEventDetail",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/CreateItemDetails",
        name: "CreateItemDetails",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/CreateItem",
        name: "CreateItem",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/InventoryItemList",
        name: "InventoryItemList",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/Error",
        name: "Error",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/ChangeConstantBase",
        name: "ChangeConstantBase",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/GoldPriceUpdateDetails",
        name: "GoldPriceUpdateDetails",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/ChangeConstantUser",
        name: "ChangeConstantUser",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/ChangeConstantGlobal",
        name: "ChangeConstantGlobal",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/ChangeConstant",
        name: "ChangeConstant",
        kind: "UNION",
        componentType: "COMPONENT",
      },
      {
        id: "#/components/schemas/GoldPriceRates",
        name: "GoldPriceRates",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/ConstantBase",
        name: "ConstantBase",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/Constant",
        name: "Constant",
        kind: "OBJECT",
        componentType: "COMPONENT",
        isCircular: false,
      },
      {
        id: "#/components/schemas/Constants",
        name: "Constants",
        kind: "OBJECT",
        componentType: "COMPONENT",
      },
    ],
    endpoints: [
      {
        operationId: "getConstants",
        method: "get",
        deprecated: false,
        path: "/constants",
      },
      {
        operationId: "upsertConstant",
        method: "post",
        deprecated: false,
        path: "/constants",
        requestBodyId: "#/components/schemas/ChangeConstant",
      },
      {
        operationId: "getInventories",
        method: "get",
        deprecated: false,
        path: "/inventory",
      },
      {
        operationId: "createInventoryItem",
        method: "post",
        deprecated: false,
        path: "/inventory",
        requestBodyId: "#/components/schemas/CreateItem",
      },
      {
        operationId: "updateInventoryItem",
        method: "put",
        deprecated: false,
        path: "/inventory/{productId}",
        requestBodyId: "#/components/schemas/UpdateItemRequest",
      },
      {
        operationId: "changeInventoryItem",
        method: "post",
        deprecated: false,
        path: "/inventory/{productId}",
        requestBodyId: "#/components/schemas/ChangeItemRequest",
      },
      {
        operationId: "getInventorySummary",
        method: "get",
        deprecated: false,
        path: "/inventory/summary",
      },
      {
        operationId: "login",
        method: "post",
        deprecated: false,
        path: "/login",
        requestBodyId: "#/components/schemas/LoginRequest",
      },
      {
        operationId: "register",
        method: "post",
        deprecated: false,
        path: "/register",
        requestBodyId: "#/components/schemas/LoginRequest",
      },
      {
        operationId: "importInventory",
        method: "post",
        deprecated: false,
        path: "/import/inventory",
      },
      {
        operationId: "saveInventory",
        method: "post",
        deprecated: false,
        path: "/save/inventory",
      },
    ],
    parameters: [
      {
        id: "updateInventoryItem::productId",
        operationId: "updateInventoryItem",
        name: "productId",
        schemaId: "productIdSchema",
        isRequired: true,
        type: "path",
      },
      {
        id: "changeInventoryItem::productId",
        operationId: "changeInventoryItem",
        name: "productId",
        schemaId: "productIdSchema",
        isRequired: true,
        type: "path",
      },
    ],
    responses: [
      {
        id: "getConstants::200",
        operationId: "getConstants",
        description: "Success",
        status: 200,
        format: "json",
        schemaId: "#/components/schemas/Constants",
      },
      {
        id: "upsertConstant::200",
        operationId: "upsertConstant",
        description: "Success",
        status: 200,
        format: "json",
        schemaId: "#/components/schemas/Constants",
      },
      {
        id: "upsertConstant::400",
        operationId: "upsertConstant",
        description: "Bad request",
        status: 400,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "getInventories::200",
        operationId: "getInventories",
        description: "Success",
        status: 200,
        format: "json",
        schemaId: "#/components/schemas/InventoryItemList",
      },
      {
        id: "createInventoryItem::201",
        operationId: "createInventoryItem",
        description: "Success",
        status: 201,
        format: "json",
        schemaId: "#/components/schemas/InventoryItem",
      },
      {
        id: "createInventoryItem::400",
        operationId: "createInventoryItem",
        description: "Bad request",
        status: 400,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "updateInventoryItem::201",
        operationId: "updateInventoryItem",
        description: "Success",
        status: 201,
        format: "json",
        schemaId: "#/components/schemas/SuccessResponse",
      },
      {
        id: "updateInventoryItem::400",
        operationId: "updateInventoryItem",
        description: "Bad request",
        status: 400,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "updateInventoryItem::404",
        operationId: "updateInventoryItem",
        description: "Not found",
        status: 404,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "changeInventoryItem::201",
        operationId: "changeInventoryItem",
        description: "Success",
        status: 201,
        format: "json",
        schemaId: "#/components/schemas/SuccessResponse",
      },
      {
        id: "changeInventoryItem::400",
        operationId: "changeInventoryItem",
        description: "Bad request",
        status: 400,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "changeInventoryItem::404",
        operationId: "changeInventoryItem",
        description: "Not found",
        status: 404,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "getInventorySummary::200",
        operationId: "getInventorySummary",
        description: "Success",
        status: 200,
        format: "json",
        schemaId: "#/components/schemas/InventorySummaryResponse",
      },
      {
        id: "getInventorySummary::401",
        operationId: "getInventorySummary",
        description: "Unauthorized",
        status: 401,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "login::201",
        operationId: "login",
        description: "Successfully logged in",
        status: 201,
        format: "json",
        schemaId: "#/components/schemas/LoginResponse",
      },
      {
        id: "login::400",
        operationId: "login",
        description: "Bad request",
        status: 400,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "login::401",
        operationId: "login",
        description: "Unauthorized",
        status: 401,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "login::404",
        operationId: "login",
        description: "Not found",
        status: 404,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "register::201",
        operationId: "register",
        description: "Successfully registered",
        status: 201,
        format: "json",
        schemaId: "#/components/schemas/RegisterResponse",
      },
      {
        id: "register::400",
        operationId: "register",
        description: "Bad request",
        status: 400,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "register::401",
        operationId: "register",
        description: "Unauthorized",
        status: 401,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "importInventory::500",
        operationId: "importInventory",
        description: "Server error",
        status: 500,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
      {
        id: "saveInventory::500",
        operationId: "saveInventory",
        description: "Server error",
        status: 500,
        format: "json",
        schemaId: "#/components/schemas/Error",
      },
    ],
    requests: [
      {
        id: "upsertConstant::#/components/schemas/ChangeConstant",
        operationId: "upsertConstant",
        parameterIds: [],
        format: "json",
      },
      {
        id: "createInventoryItem::#/components/schemas/CreateItem",
        operationId: "createInventoryItem",
        parameterIds: [],
        format: "json",
      },
      {
        id: "updateInventoryItem::#/components/schemas/UpdateItemRequest",
        operationId: "updateInventoryItem",
        parameterIds: ["updateInventoryItem::productId"],
        format: "json",
      },
      {
        id: "changeInventoryItem::#/components/schemas/ChangeItemRequest",
        operationId: "changeInventoryItem",
        parameterIds: ["changeInventoryItem::productId"],
        format: "json",
      },
      {
        id: "login::#/components/schemas/LoginRequest",
        operationId: "login",
        parameterIds: [],
        format: "json",
      },
      {
        id: "register::#/components/schemas/LoginRequest",
        operationId: "register",
        parameterIds: [],
        format: "json",
      },
    ],
  } as const;
}

export default App;
